### ISSUE TITLE
Better way to do cobwebs

### ISSUE THREAD

**Issue by Zweihorn** [Irremann/mobs_spider#1]
Don't want to bother you and I don't know if this is an active project.

However, I want to make you aware of the thread [Better way to do cobwebs](https://forum.minetest.net/viewtopic.php?f=47&t=28938) in the Minetest forum. Just incase if you would consider further development with your WIP mod.

**Comment by Irremann** [comment]
The mod has been working on my server for 3 years. There is only a mobkit and a cobweb from xdecor. It's just that the players asked for spiders that do not spawn under the house and hiss dumbly. So here are the kind silent red-eyed spiders that do not hiss! So feel free to use it.

**Comment by Zweihorn** [comment]
Good to know. Looks fair to me and thank you for this update.

Happy coding and have fun.

closed
